sudo: required

language: php

php:
  - 7.0
  - 7.1

services:
  - rabbitmq

env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - if [ $TRAVIS_PHP_VERSION = "7.0" ]; then phpenv config-rm xdebug.ini; fi
  - sudo cp $TRAVIS_BUILD_DIR/provision/rabbitmq.config /etc/rabbitmq/
  - sudo service rabbitmq-server restart
  - echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer update --prefer-dist $DEPENDENCIES
  - sudo rabbitmqctl add_vhost /humus-amqp-test
  - sudo rabbitmqctl set_permissions -p /humus-amqp-test guest ".*" ".*" ".*"

script:
  - php -dzend_extension=xdebug.so ./vendor/bin/phpunit --exclude-group=ssl --coverage-text --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/php-cs-fixer fix -v --diff --dry-run
  - ./vendor/bin/docheader check src/ tests/

after_success:
  - php vendor/bin/coveralls -v
